title = "Gitleaks configuration"

[extend]
useDefault = true

[[allowlists]]
description = "Ignore Yarn"
paths = [
    "packages/@juspay-tech/react-native-hyperswitch-cardinal-3ds/.yarn/releases/yarn-3.6.1.cjs",
    "packages/@juspay-tech/react-native-hyperswitch-authentication-module/.yarn/releases/yarn-3.6.1.cjs",
    "packages/@juspay-tech/react-native-hyperswitch-trident-3ds/.yarn/releases/yarn-3.6.1.cjs"
]
regexes = ["/*In.isRecognitionException=void*/"]
